name: Build My Tool
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4 # Aktualizacja do v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4 # Aktualizacja do v4
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Upload
        uses: actions/upload-artifact@v4 # Naprawa błędu - Aktualizacja do v4
        with:
          name: Program-Gotowy
          path: bin/Release/net6.0-windows/win-x64/publish/Ak0Analyzer.exe
